name: Github CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install
      run: npm ci

    - name: Lint commit messages
      run: npx commitlint --from origin/master --to HEAD

    - name: Test (ESLint)
      run: npm test

    - name: Semantic release
      run: npx semantic-release
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
